[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com;"

[[plugins]]
  package = "@netlify/plugin-functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/login"
  status = 200
  conditions = {Role = ["!authenticated"]} 